#PBS -q route
#PBS -N MO644-Plasma
#PBS -o plasma-job.out
#PBS -e plasma-job.err
#PBS -V
#PBS -l walltime=00:50:00
#PBS -l select=5:ncpus=40:ngpus=0:Qlist=Allnodes
#!/bin/sh

# The header above specifies the resources that the job can use.
# The last line of the header works as follow:
# select=<number of nodes>:ncpus=<cores per node>:
# ngpus=<gpu per nodes>:Qlist=<computer list>

# Change current folder to job directory
cd $PBS_O_WORKDIR

# Singularity image path
SIF_IMG=/scratch/rodrigofreitas/ompcluster/plasma-dev_latest.sif

# Load required modules and environment configuration
. $HOME/.bashrc
source /etc/profile.d/modules.sh
module purge
module load mpich/mpich2-1.4.1
module load singularity/singularity-3.0.3

export CC=clang
export CXX=clang++

# Disable FT to fix a problem with large dataset
export LIBOMPTARGET_FT_DISABLE=1

# Build MPI hostfile to use nodes with high-speed Infiniband network (IB)
cat $PBS_NODEFILE > temp$PBS_JOBID.txt
echo "" > hostfile$PBS_JOBID.txt
uniq temp$PBS_JOBID.txt | awk -F "." '{print $1"-ib0"}' >> hostfile$PBS_JOBID.txt
rm temp$PBS_JOBID.txt
sed -i 1d hostfile$PBS_JOBID.txt

ALLOCATED_NODES=$(cat hostfile$PBS_JOBID.txt|wc -l)
echo "Got $ALLOCATED_NODES nodes!"

# Execute PLASMA within OmpCluster container using Singularity
export OMP_NUM_THREADS=24
#mpirun -hostfile hostfile$PBS_JOBID.txt -ppn 1 singularity exec $SIF_IMG ./plasmatest dgemm --dim=4 --nb=2 --test=y
singularity exec $SIF_IMG ./build/plasmatest dgemm --dim=24 --nb=8 --test=y



# Remove build folder and hostfile
rm -rf hostfile$PBS_JOBID.txt
